# Generated by Django 5.2.6 on 2025-09-23 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactsubmission_delete_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
